# Generated by Django 4.2.26 on 2026-02-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
                'db_table': 'game_answer',
                'ordering': ('answered_at',),
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('eng_ukr', 'Англійська → Українська'), ('ukr_eng', 'Українська → Англійська')], max_length=10)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='simulator.topic')),
            ],
            options={
                'verbose_name': 'Сессія гри',
                'verbose_name_plural': 'Сессії гри',
                'db_table': 'game_session',
                'ordering': ('-created_at',),
            },
        ),
    ]
