# Generated by Django 4.2.26 on 2026-02-02 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('simulator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.gamesession'),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.word'),
        ),
        migrations.AlterUniqueTogether(
            name='gameanswer',
            unique_together={('session', 'word')},
        ),
    ]
