# Generated by Django 4.2.26 on 2026-02-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='mode',
            field=models.CharField(choices=[('full', 'Full'), ('mistakes', 'Mistakes')], default='full', max_length=10),
        ),
    ]
