# Generated by Django 4.2.26 on 2026-02-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanswer',
            name='user_answer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
